name: Test Incoming Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Run Linter and Vet
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.sha }}

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version-file: go.mod

      - name: Disable default go problem matcher
        run: echo "::remove-matcher owner=go::"

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 10m0s

      - name: make vet
        run: make vet
